### ISSUE TITLE
Typo for this flag --query-frontend.log-queries-longer-than

### ISSUE THREAD

**Issue by pavan541cs** [banzaicloud/thanos-operator#144]
**Describe the bug**
Query Frontend supports --query-frontend.log-queries-longer-than flag to log queries running longer than some duration.
The flag is wrongly hardcoded in the thanos operator. _(underscore) is in place instead of -(hiphen)
https://github.com/banzaicloud/thanos-operator/blob/master/pkg/sdk/api/v1alpha1/thanos_types.go#L141

**Expected behavior**
 --query-frontend.log-queries-longer-than - This is flag expected by thanos querier frontend

**Comment by pavan541cs** [comment]
@pepov Any comment on this issue ?

**Comment by pepov** [comment]
Yes, that seems correct, could by any chance open a pr for that? If not I can do that later.

**Comment by pavan541cs** [comment]
@pepov Raised #145  for the same
