### ISSUE TITLE
Thanos store uses ephemeral storage and fills up the Node storage.

### ISSUE THREAD

**Issue by dpachiappan** [banzaicloud/thanos-operator#153]
**Describe the bug**
Thanos operator is used for deploying the the thanos components (storegateway, query, query frontend).

Thanos store container fills up the ephemeral disk that is only 50GB.

Tried configuring the PVC for the store container, but the operator is not accepting the additional PVC volume and gives the below error.

thanos> Reconciler error failed to reconcile resource: failed to create resource: creating resource failed: Deployment.apps "sandbox-us-west-2-thanos-cluster-store" is invalid: spec.template.spec.volumes[0].persistentVolumeClaim: Forbidden: may not specify more than 1 volume type (name: sandbox-us-west-2-thanos-cluster-store, namespace: monitoring, apiVersion: apps/v1, kind: Deployment, name: sandbox-us-west-2-thanos-cluster-store, namespace: monitoring, apiVersion: apps/v1, kind: Deployment) name: sandbox-us-west-2, namespace: monitoring

Here is my Thanos store gateway config input given to Thanos CR.

storeGateway:
indexCacheSize: 250MB
deploymentOverrides:
spec:
template:
spec:
containers:
- image:thanos/thanos:v0.19.0-rc.0
imagePullPolicy: Always
name: store
volumeMounts:
- mountPath: /data
name: task-pv-storage
volumes:
- name: task-pv-storage
persistentVolumeClaim:
claimName: clusterstore-pvc

This issue is not happening in other clusters where the ephemeral disk is 100GB. I tried configuring the IndexCacheSize to 10GB, and it is still not taking effect.

Have anyone encountered this issue?

How do we configure the Thanos store Gateway to use the PVC or configure the object download limit on the ephemeral disk?

Thanos Operator details:

Thanos Version: thanos:v0.19.0-rc.0

Thanos Operator Version: 0.3.3

Object Storage Provider: S3

**Comment by pepov** [comment]
It seems that the merge doesn't work right in this case, I can reproduce it in master as well. I have to look into how we can fix this.

**Comment by dpachiappan** [comment]
> It seems that the merge doesn't work right in this case, I can reproduce it in master as well. I have to look into how we can fix this.

Thanks.   So, the PVC attachment is forbidden by the operator validation on Purpose?

**Comment by pepov** [comment]
No, this is a bug.

**Comment by pepov** [comment]
Please try 0.3.4, which should now support the above override configuration properly.
