### ISSUE TITLE
Implement Thanos Query Frontend

### ISSUE THREAD

**Issue by SuperQ** [banzaicloud/thanos-operator#45]
**Is your feature request related to a problem? Please describe.**

Thanos 0.15.0 now includes a [Query Frontend](https://thanos.io/tip/components/query-frontend/) component. The operator should be able to deploy this.

**Comment by SuperQ** [comment]
We're looking to use the thanos-operator at GitLab, so I'm going to try and implement this.

**Comment by tarokkk** [comment]
Hi I hope I'm not late but I started to work on this, and hope to make the PR this week

**Comment by trynity** [comment]
Seems like this got implemented with https://github.com/banzaicloud/thanos-operator/pull/49

**Comment by SuperQ** [comment]
Great!
