### ISSUE TITLE
jsonnet library distribution

### ISSUE THREAD

**Issue by craigfurman** [banzaicloud/thanos-operator#68]
**Is your feature request related to a problem? Please describe.**

The thanos-operator is distributed by helm chart. While the operator's Deployment is simple enough to recreate, there are lengthy, relatively non-customizable CRD and ClusterRole declarations in this repository that helm non-users have to keep up with.

**Describe the solution you'd like to see**

What do you think of publishing a jsonnet library for the operator's resources, similar to https://github.com/prometheus-operator/kube-prometheus?

This would allow the operator to be easily consumed by jsonnet-based deployment systems, such as https://tanka.dev.

**Describe alternatives you've considered**

**Additional context**

If you're interested in this idea, I'm happy to try to PR it.

**Comment by tarokkk** [comment]
I don't have much jsonet experience but if you want to contribute an installer (shouldn't be hard) open a PR ;)

**Comment by craigfurman** [comment]
Sorry @tarokkk, since I filed this issue I've actually moved away from thanos-operator to kube-thanos (https://github.com/thanos-io/kube-thanos), configuring thanos' resources without new CRDs, so I'm unlikely to get back to this. Feel free to close.

**Comment by tarokkk** [comment]
Sure thank you
